start dotnet Supercell.Magic.Servers.Proxy/bin/Debug/netcoreapp2.2/Supercell.Magic.Servers.Proxy.dll
start dotnet Supercell.Magic.Servers.Account/bin/Debug/netcoreapp2.2/Supercell.Magic.Servers.Account.dll
start dotnet Supercell.Magic.Servers.Game/bin/Debug/netcoreapp2.2/Supercell.Magic.Servers.Game.dll
start dotnet Supercell.Magic.Servers.Home/bin/Debug/netcoreapp2.2/Supercell.Magic.Servers.Home.dll
start dotnet Supercell.Magic.Servers.Chat/bin/Debug/netcoreapp2.2/Supercell.Magic.Servers.Chat.dll
start dotnet Supercell.Magic.Servers.Alliance/bin/Debug/netcoreapp2.2/Supercell.Magic.Servers.Alliance.dll
start dotnet Supercell.Magic.Servers.Search/bin/Debug/netcoreapp2.2/Supercell.Magic.Servers.Search.dll
start dotnet Supercell.Magic.Servers.Stream/bin/Debug/netcoreapp2.2/Supercell.Magic.Servers.Stream.dll
start dotnet Supercell.Magic.Servers.Admin/bin/Debug/netcoreapp2.2/Supercell.Magic.Servers.Admin.dll